name: CVHome
main: org.cubeville.cvhome.CVHome
author: mciolkosz
version: 1.1
api-version: 1.15

depend: [CVTools]

commands:
  sethome:
    description: Command to set the player's home location
    permission: cvhome.command.sethome
    permission-message: §cNo permission.
    usage: "§cSyntax: /sethome"
    aliases: homeset
  home:
    description: Command to teleport to the player's home location
    permission: cvhome.command.home
    permission-message: §cNo permission.
    usage: "§cSyntax: /home"
  homeinfo:
    description: Command to get the player's home location information.
    permission: cvhome.command.homeinfo
    permission-message: §cNo permission.
    usage: "§cSyntax: /homeinfo"
    aliases: infohome

permissions:
  cvhome.max.2:
    description: Maximum of 2 homes
    default: op
  cvhome.max.3:
    description: Maximum of 3 homes
    default: false
  cvhome.max.4:
    description: Maximum of 4 homes
    default: false
  cvhome.command.sethome:
    description: Permission to use the /sethome command
    default: true
  cvhome.command.sethome.other:
    description: Permission to use the /sethome command to set another player's home
    default: op
  cvhome.command.home:
    description: Permission to use the /home command
    default: true
  cvhome.command.home.other:
    description: Permission to use the /home command to teleport to another player's home
    default: op
  cvhome.command.homeinfo:
    description: Permission to use the /homeinfo command
    default: op
  cvhome.command.homeinfo.other:
    description: Permission to use the /homeinfo command to view information about another player's home
    default: op
